In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv("//content//amazon.csv",delimiter=',')
data

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,₹399,"₹1,099",64%,4.2,"24,269",High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,₹199,₹349,43%,4.0,"43,994","Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,₹199,"₹1,899",90%,3.9,"7,928",【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,₹329,₹699,53%,4.2,"94,363",The boAt Deuce USB 300 2 in 1 cable is compati...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou...",https://m.media-amazon.com/images/I/41V5FtEWPk...,https://www.amazon.in/Deuce-300-Resistant-Tang...
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,₹154,₹399,61%,4.2,"16,905",[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Portronics-Konnect-POR-1...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1460,B08L7J3T31,Noir Aqua - 5pcs PP Spun Filter + 1 Spanner | ...,Home&Kitchen|Kitchen&HomeAppliances|WaterPurif...,₹379,₹919,59%,4,"1,090",SUPREME QUALITY 90 GRAM 3 LAYER THIK PP SPUN F...,"AHITFY6AHALOFOHOZEOC6XBP4FEA,AFRABBODZJZQB6Z4U...","Prabha ds,Raghuram bk,Real Deal,Amazon Custome...","R3G3XFHPBFF0E8,R3C0BZCD32EIGW,R2EBVBCN9QPD9R,R...","Received the product without spanner,Excellent...","I received product without spanner,Excellent p...",https://m.media-amazon.com/images/I/41fDdRtjfx...,https://www.amazon.in/Noir-Aqua-Spanner-Purifi...
1461,B01M6453MB,Prestige Delight PRWO Electric Rice Cooker (1 ...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,"₹2,280","₹3,045",25%,4.1,"4,118","230 Volts, 400 watts, 1 Year","AFG5FM3NEMOL6BNFRV2NK5FNJCHQ,AGEINTRN6Z563RMLH...","Manu Bhai,Naveenpittu,Evatira Sangma,JAGANNADH...","R3DDL2UPKQ2CK9,R2SYYU1OATVIU5,R1VM993161IYRW,R...","ok,everything was good couldn't return bcoz I ...","ok,got everything as mentioned but the measuri...",https://m.media-amazon.com/images/I/41gzDxk4+k...,https://www.amazon.in/Prestige-Delight-PRWO-1-...
1462,B009P2LIL4,Bajaj Majesty RX10 2000 Watts Heat Convector R...,"Home&Kitchen|Heating,Cooling&AirQuality|RoomHe...","₹2,219","₹3,080",28%,3.6,468,International design and styling|Two heat sett...,"AGVPWCMAHYQWJOQKMUJN4DW3KM5Q,AF4Q3E66MY4SR7YQZ...","Nehal Desai,Danish Parwez,Amazon Customer,Amaz...","R1TLRJVW4STY5I,R2O455KRN493R1,R3Q5MVGBRIAS2G,R...","very good,Work but front melt after 2 month,Go...","plastic but cool body ,u have to find sturdy s...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Bajaj-RX-10-2000-Watt-Co...
1463,B00J5DYCCA,Havells Ventil Air DSP 230mm Exhaust Fan (Pist...,"Home&Kitchen|Heating,Cooling&AirQuality|Fans|E...","₹1,399","₹1,890",26%,4,"8,031",Fan sweep area: 230 MM ; Noise level: (40 - 45...,"AF2JQCLSCY3QJATWUNNHUSVUPNQQ,AFDMLUXC5LS5RXDJS...","Shubham Dubey,E.GURUBARAN,Mayank S.,eusuf khan...","R39Q2Y79MM9SWK,R3079BG1NIH6MB,R29A31ZELTZNJM,R...","Fan Speed is slow,Good quality,Good product,go...",I have installed this in my kitchen working fi...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Havells-Ventilair-230mm-...
1464,B01486F4G6,Borosil Jumbo 1000-Watt Grill Sandwich Maker (...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,"₹2,863","₹3,690",22%,4.3,"6,987","Brand-Borosil, Specification â€“ 23V ~ 5Hz;1 W...","AFGW5PT3R6ZAVQR4Y5MWVAKBZAYA,AG7QNJ2SCS5VS5VYY...","Rajib,Ajay B,Vikas Kahol,PARDEEP,Anindya Prama...","R20RBRZ0WEUJT9,ROKIFK9R2ISSE,R30EEG2FNJSN5I,R2...","Works perfect,Ok good product,Nice Product. Re...",It does it job perfectly..only issue is temp c...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Borosil-Jumbo-1000-Watt-...

In [ ]:
data.info()
data.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1465 non-null   object
 1   product_name         1465 non-null   object
 2   category             1465 non-null   object
 3   discounted_price     1465 non-null   object
 4   actual_price         1465 non-null   object
 5   discount_percentage  1465 non-null   object
 6   rating               1465 non-null   object
 7   rating_count         1463 non-null   object
 8   about_product        1465 non-null   object
 9   user_id              1465 non-null   object
 10  user_name            1465 non-null   object
 11  review_id            1465 non-null   object
 12  review_title         1465 non-null   object
 13  review_content       1465 non-null   object
 14  img_link             1465 non-null   object
 15  product_link         1465 non-null   object
dtypes: object(16)
memory usage: 183.3+ KB

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
count,1465,1465,1465,1465,1465,1465,1465,1463,1465,1465,1465,1465,1465,1465,1465,1465
unique,1351,1337,211,550,449,92,28,1143,1293,1194,1194,1194,1194,1212,1412,1465
top,B083342NKJ,"Fire-Boltt Ninja Call Pro Plus 1.83"" Smart Wat...",Computers&Accessories|Accessories&Peripherals|...,₹199,₹999,50%,4.1,"9,378",[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AHIKJUDTVJ4T6DV6IUGFYZ5LXMPA,AE55KTFVNXYFD5FPY...","$@|\|TO$|-|,Sethu madhav,Akash Thakur,Burger P...","R3F4T5TRYPTMIG,R3DQIEC603E7AY,R1O4Z15FD40PV5,R...","Worked on iPhone 7 and didn’t work on XR,Good ...","I am not big on camera usage, personally. I wa...",https://m.media-amazon.com/images/I/413sCRKobN...,https://www.amazon.in/Borosil-Jumbo-1000-Watt-...
freq,3,5,233,53,120,56,244,9,6,10,10,10,10,8,3,1

In [ ]:
data.head()

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,₹399,"₹1,099",64%,4.2,"24,269",High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,₹199,₹349,43%,4.0,"43,994","Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,₹199,"₹1,899",90%,3.9,"7,928",【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,₹329,₹699,53%,4.2,"94,363",The boAt Deuce USB 300 2 in 1 cable is compati...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou...",https://m.media-amazon.com/images/I/41V5FtEWPk...,https://www.amazon.in/Deuce-300-Resistant-Tang...
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,₹154,₹399,61%,4.2,"16,905",[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Portronics-Konnect-POR-1...

In [ ]:
data.tail()

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
1460,B08L7J3T31,Noir Aqua - 5pcs PP Spun Filter + 1 Spanner | ...,Home&Kitchen|Kitchen&HomeAppliances|WaterPurif...,₹379,₹919,59%,4,"1,090",SUPREME QUALITY 90 GRAM 3 LAYER THIK PP SPUN F...,"AHITFY6AHALOFOHOZEOC6XBP4FEA,AFRABBODZJZQB6Z4U...","Prabha ds,Raghuram bk,Real Deal,Amazon Custome...","R3G3XFHPBFF0E8,R3C0BZCD32EIGW,R2EBVBCN9QPD9R,R...","Received the product without spanner,Excellent...","I received product without spanner,Excellent p...",https://m.media-amazon.com/images/I/41fDdRtjfx...,https://www.amazon.in/Noir-Aqua-Spanner-Purifi...
1461,B01M6453MB,Prestige Delight PRWO Electric Rice Cooker (1 ...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,"₹2,280","₹3,045",25%,4.1,"4,118","230 Volts, 400 watts, 1 Year","AFG5FM3NEMOL6BNFRV2NK5FNJCHQ,AGEINTRN6Z563RMLH...","Manu Bhai,Naveenpittu,Evatira Sangma,JAGANNADH...","R3DDL2UPKQ2CK9,R2SYYU1OATVIU5,R1VM993161IYRW,R...","ok,everything was good couldn't return bcoz I ...","ok,got everything as mentioned but the measuri...",https://m.media-amazon.com/images/I/41gzDxk4+k...,https://www.amazon.in/Prestige-Delight-PRWO-1-...
1462,B009P2LIL4,Bajaj Majesty RX10 2000 Watts Heat Convector R...,"Home&Kitchen|Heating,Cooling&AirQuality|RoomHe...","₹2,219","₹3,080",28%,3.6,468,International design and styling|Two heat sett...,"AGVPWCMAHYQWJOQKMUJN4DW3KM5Q,AF4Q3E66MY4SR7YQZ...","Nehal Desai,Danish Parwez,Amazon Customer,Amaz...","R1TLRJVW4STY5I,R2O455KRN493R1,R3Q5MVGBRIAS2G,R...","very good,Work but front melt after 2 month,Go...","plastic but cool body ,u have to find sturdy s...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Bajaj-RX-10-2000-Watt-Co...
1463,B00J5DYCCA,Havells Ventil Air DSP 230mm Exhaust Fan (Pist...,"Home&Kitchen|Heating,Cooling&AirQuality|Fans|E...","₹1,399","₹1,890",26%,4,"8,031",Fan sweep area: 230 MM ; Noise level: (40 - 45...,"AF2JQCLSCY3QJATWUNNHUSVUPNQQ,AFDMLUXC5LS5RXDJS...","Shubham Dubey,E.GURUBARAN,Mayank S.,eusuf khan...","R39Q2Y79MM9SWK,R3079BG1NIH6MB,R29A31ZELTZNJM,R...","Fan Speed is slow,Good quality,Good product,go...",I have installed this in my kitchen working fi...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Havells-Ventilair-230mm-...
1464,B01486F4G6,Borosil Jumbo 1000-Watt Grill Sandwich Maker (...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,"₹2,863","₹3,690",22%,4.3,"6,987","Brand-Borosil, Specification â€“ 23V ~ 5Hz;1 W...","AFGW5PT3R6ZAVQR4Y5MWVAKBZAYA,AG7QNJ2SCS5VS5VYY...","Rajib,Ajay B,Vikas Kahol,PARDEEP,Anindya Prama...","R20RBRZ0WEUJT9,ROKIFK9R2ISSE,R30EEG2FNJSN5I,R2...","Works perfect,Ok good product,Nice Product. Re...",It does it job perfectly..only issue is temp c...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Borosil-Jumbo-1000-Watt-...

In [ ]:
data.isnull()

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1460,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1461,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1462,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1463,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1464,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
data.isnull().sum()

product_id             0
product_name           0
category               0
discounted_price       0
actual_price           0
discount_percentage    0
rating                 0
rating_count           2
about_product          0
user_id                0
user_name              0
review_id              0
review_title           0
review_content         0
img_link               0
product_link           0
dtype: int64

In [ ]:
data['rating_count']

0       24,269
1       43,994
2        7,928
3       94,363
4       16,905
         ...
1460     1,090
1461     4,118
1462       468
1463     8,031
1464     6,987
Name: rating_count, Length: 1465, dtype: object

In [ ]:
data.dropna()

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,₹399,"₹1,099",64%,4.2,"24,269",High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,₹199,₹349,43%,4.0,"43,994","Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,₹199,"₹1,899",90%,3.9,"7,928",【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,₹329,₹699,53%,4.2,"94,363",The boAt Deuce USB 300 2 in 1 cable is compati...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou...",https://m.media-amazon.com/images/I/41V5FtEWPk...,https://www.amazon.in/Deuce-300-Resistant-Tang...
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,₹154,₹399,61%,4.2,"16,905",[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Portronics-Konnect-POR-1...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1460,B08L7J3T31,Noir Aqua - 5pcs PP Spun Filter + 1 Spanner | ...,Home&Kitchen|Kitchen&HomeAppliances|WaterPurif...,₹379,₹919,59%,4,"1,090",SUPREME QUALITY 90 GRAM 3 LAYER THIK PP SPUN F...,"AHITFY6AHALOFOHOZEOC6XBP4FEA,AFRABBODZJZQB6Z4U...","Prabha ds,Raghuram bk,Real Deal,Amazon Custome...","R3G3XFHPBFF0E8,R3C0BZCD32EIGW,R2EBVBCN9QPD9R,R...","Received the product without spanner,Excellent...","I received product without spanner,Excellent p...",https://m.media-amazon.com/images/I/41fDdRtjfx...,https://www.amazon.in/Noir-Aqua-Spanner-Purifi...
1461,B01M6453MB,Prestige Delight PRWO Electric Rice Cooker (1 ...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,"₹2,280","₹3,045",25%,4.1,"4,118","230 Volts, 400 watts, 1 Year","AFG5FM3NEMOL6BNFRV2NK5FNJCHQ,AGEINTRN6Z563RMLH...","Manu Bhai,Naveenpittu,Evatira Sangma,JAGANNADH...","R3DDL2UPKQ2CK9,R2SYYU1OATVIU5,R1VM993161IYRW,R...","ok,everything was good couldn't return bcoz I ...","ok,got everything as mentioned but the measuri...",https://m.media-amazon.com/images/I/41gzDxk4+k...,https://www.amazon.in/Prestige-Delight-PRWO-1-...
1462,B009P2LIL4,Bajaj Majesty RX10 2000 Watts Heat Convector R...,"Home&Kitchen|Heating,Cooling&AirQuality|RoomHe...","₹2,219","₹3,080",28%,3.6,468,International design and styling|Two heat sett...,"AGVPWCMAHYQWJOQKMUJN4DW3KM5Q,AF4Q3E66MY4SR7YQZ...","Nehal Desai,Danish Parwez,Amazon Customer,Amaz...","R1TLRJVW4STY5I,R2O455KRN493R1,R3Q5MVGBRIAS2G,R...","very good,Work but front melt after 2 month,Go...","plastic but cool body ,u have to find sturdy s...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Bajaj-RX-10-2000-Watt-Co...
1463,B00J5DYCCA,Havells Ventil Air DSP 230mm Exhaust Fan (Pist...,"Home&Kitchen|Heating,Cooling&AirQuality|Fans|E...","₹1,399","₹1,890",26%,4,"8,031",Fan sweep area: 230 MM ; Noise level: (40 - 45...,"AF2JQCLSCY3QJATWUNNHUSVUPNQQ,AFDMLUXC5LS5RXDJS...","Shubham Dubey,E.GURUBARAN,Mayank S.,eusuf khan...","R39Q2Y79MM9SWK,R3079BG1NIH6MB,R29A31ZELTZNJM,R...","Fan Speed is slow,Good quality,Good product,go...",I have installed this in my kitchen working fi...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Havells-Ventilair-230mm-...
1464,B01486F4G6,Borosil Jumbo 1000-Watt Grill Sandwich Maker (...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,"₹2,863","₹3,690",22%,4.3,"6,987","Brand-Borosil, Specification â€“ 23V ~ 5Hz;1 W...","AFGW5PT3R6ZAVQR4Y5MWVAKBZAYA,AG7QNJ2SCS5VS5VYY...","Rajib,Ajay B,Vikas Kahol,PARDEEP,Anindya Prama...","R20RBRZ0WEUJT9,ROKIFK9R2ISSE,R30EEG2FNJSN5I,R2...","Works perfect,Ok good product,Nice Product. Re...",It does it job perfectly..only issue is temp c...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Borosil-Jumbo-1000-Watt-...

In [ ]:
data['about_product']

0       High Compatibility : Compatible With iPhone 12...
1       Compatible with all Type C enabled devices, be...
2       【 Fast Charger& Data Sync】-With built-in safet...
3       The boAt Deuce USB 300 2 in 1 cable is compati...
4       [CHARGE & SYNC FUNCTION]- This cable comes wit...
                              ...
1460    SUPREME QUALITY 90 GRAM 3 LAYER THIK PP SPUN F...
1461                         230 Volts, 400 watts, 1 Year
1462    International design and styling|Two heat sett...
1463    Fan sweep area: 230 MM ; Noise level: (40 - 45...
1464    Brand-Borosil, Specification â€“ 23V ~ 5Hz;1 W...
Name: about_product, Length: 1465, dtype: object

In [ ]:
d = pd.Categorical(data['about_product'])
print(d)

['High Compatibility : Compatible With iPhone 1..., 'Compatible with all Type C enabled devices, b..., '【 Fast Charger& Data Sync】-With built-in safe..., 'The boAt Deuce USB 300 2 in 1 cable is compat..., '[CHARGE & SYNC FUNCTION]- This cable comes wi..., ..., 'SUPREME QUALITY 90 GRAM 3 LAYER THIK PP SPUN ..., '230 Volts, 400 watts, 1 Year', 'International design and styling|Two heat set..., 'Fan sweep area: 230 MM ; Noise level: (40 - 4..., 'Brand-Borosil, Specification â€“ 23V ~ 5Hz;1 ...]
Length: 1465
Categories (1293, object): ['*Please match your previous remote before pla..., '*Please match your previous remote before pla...,
                            '-1 meter type c to c cable fast charging cabl..., '-Easy to attach, remove and wash.|-Protect fr...,
                            ..., '📞【UTMOST CUSTOMER SUPPORT: 】24 hours WhatsApp...,
                            '🔥PTC CERAMIC CHIP HEATING TECHNOLOGY: The EOP..., '🛒【CableCreation RCA Cable】:Great for connecti...,
                            '🥇【Kindly NOTE before you purchase】:This is a ...]

In [ ]:
pd.get_dummies(data['about_product'],dtype=int)

,*Please match your previous remote before placing order. or for verification of remote contact our coustmer care 7738090464,*Please match your previous remote before placing order. or for verification of remote contact our coustmer care 7738090464|. * Its Electvision compatible remote for kodak LED.,"-1 meter type c to c cable fast charging cable Convenient for all types of USB C Laptops, Tablets, And Smartphones.|-6.5 Amp USB C Cable compatibility with All 60W 45W 30W 18W 15W USB-C Power Adapters, Support Pd 3.0 And Qc 3.0 Fast Charge for Your Devices. Data Transfer Speed Is Up To 480Mbps Of USB 2.0. Note: Not Support Video Transfer.AM|-USB C To C Cable Support Warp Charge For One plus 8T, One plus 9/9 Pro, Too Fast Charge For MacBook Air 13 Inch 2020/2019/2018, For MacBook Pro 13/15/16 Inch AM|Compatiblity with type c to c cable fast charging cabe is Newest 2020/2019/2018/2017/2016, For iPad Mini 2021, For iPad Pro 12.9/11 Inch 2020, For Google Pixel 6/6 Pro/5/4A/4 Xl/4/3A Xl/3A/3 Xl/3/2 Xl/2, For Samsung Galaxy S21 Fe 5G/S20 Fe 5G/Note 20 Ultra/Note 20/S20/S20+/S20 Ultra, Galaxy Z Flip 3, Galaxy Z Fold 3, And More Devices.|65 watt type c cable is in Premium Silicon Coating, High-Quality, Prolong Bending Lifespan , Pure Copper Core, . Both USB C Connectors are Designed with An Advanced Emark Chip for Higher Efficiency & Safer Charging for Your One plus 8T. Output Delivery At 6.5A 10V Max, 65% Charging Capacity Only Takes 30 Minutes, Saving Your Valued Time.","-Easy to attach, remove and wash.|-Protect from food and water spillage.|-Suitable for 15.6Inch Laptop Silicone Keyboard Protector Keyguard.|-Keep your laptop keyboard protected from dust and water spilling.|-Its transparent colour, keeps the original texture and look of the keyboard.",-High performance Micro USB 3.0 hard disk cable connects a portable external USB 3.0 hard drive to a computer for speedy file transfer or syncs and charges tablets or smartphones or USB 3.0 Micro-B port devices|-Super Speed USB 3.0 data transfer cables are compatible with most USB 3.0 external portable and desktop hard disk connector|-USB 3.0 micro b cable offer a throughput of up to 4.8Gbps when used with a USB 3.0 host and device AK9|-Replacement USB 3.0 Cables for external hard disk wire|-Connector A: USB 3.0 A (9 pin SuperSpeed) Male Connector B: USB 3.0 Micro-B (10 pin SuperSpeed) Male Superspeed USB 3.0 hard disk cable A to Micro B (10pin) Quickly transfer data from an external storage device to your PC or Laptop at 10x the speed of USB 2.0,"-Make delicious milk foam creamer for your drinks at home without a trip to Starbucks, with your own coffee maker with milk frother. The benefits of having your own electric cold coffee maker are endless, you can make your own best coffee, you know yours tastes the best.|-Proven & Trusted Quality: We use only premium materials. Our milk frother for coffee will not rust or break, ever. Built to last.|-Easy to clean Coffee frother electric: The durable, convenient metal stand gives easy access for foaming milk in seconds. Cleanup for this portable coffee maker is even faster. To clean just put the coffee mixer blender in hot running water and briefly turn it on – instantly clean!|-Electric Coffee Frother Works better than a manual coffee hand blender for making matcha/tea and works far better than fork or Frother for coffee. It works very well to mix nutritious protein powder drinks with no extra container, blender or bottle shaker to wash. Use our mocktail mixer for your whisking and mixing needs.|-Design: our coffee beater comes with an elegant design to fit into any modern kitchen.|It requires two AA Double Batteries to start. Batteries are not INCLUDED.","-mini usb cable is easy to plug and play connections with digital cameras , mobile phones, MP3 players, PDAs, External Hard Drives.|Compatibility with USB 1.0, 1.1 and 2.0.|This Camera cable transfer your pictures from your digital camera to your PC.|Connect a peripheral with a 5-Pin Mini-USB port to an USB Hub or USB port on PC|Warranty-1 year","-mouse pad with wrist rest makes your wrist feel no-pain , reducing pressure keeping wrist at right position|-Gel on below wrist makes stress fress and comfort with rubberized base keeping pad at one place AI7|-High-quality cloth surface for smooth gliding|-Lycra fabric makes mouse pad with wrist rest tracking more accurate and smooth.dosent irritate to skin,moving mouse fast n free|- this mouse pad with wrist rest Designed for Office , Gamers, Home-Office, generally used with all types of laptops and desktop.",. The tough pure metal stainless-steel build makes it very sturdy and the inside part is only made from premium food grade stainless steel that keep your water out of the contamination from plastic materials and chemicals,"0.7 mm tip size|Black Body, Multicolor Ink(Black, Red, Green, Pink, Turquoise Blue, Orange, Blue, Brown, Purple, Lime Green), Pack of 10|Easy flow Ink Technology|Sleek Matte Finish|Featherlite feel",...,"【WATCH, PLAY, STUDY - WITHOUT LEAVING THE BED! 】- Are you an avid lover of comfy bed? or now you're recovering from a past surgery,what you need most is here! It perfectly fits a small size laptop,or tablet & phone, also read or do arts and crafts while sitting on the sofa or having breakfast in bed.|【MUTI-FUNCTIONAL DESK】 – Callas Bed Table Built-in iPad stand groove for holding ipad or kindle.And desk comes with a table cup holder to store cups well. The Anti-Slip Sponge can keep your laptop safe while tilted, and provide you comfort and stability while using.|【PORTABLE AND CONVENIENT】 – The metal legs are foldable, easily fold flat for convenient storage when you don't need it.There are handles on the table, you can easily take the table to any place you want to use it.It is very lightweight, easy to carry and play.Go out camping is also an ideal choice.|【ERGONOMIC DESIGN】–Curved desktop edge, scientific design, protective layer around the desktop, so you can feel comfortable when using. The W-legs are stable and flexible, which are anti-slip and can be folded to save space.|【LARGE SIZE】 - 23.64(L) x 15.72(W) x 10.4Inch(H). Callas Lap Desk perfectly fits nearly all size laptop,or tablet & phone, also can put a mouse and books.And there is ample space to work, study, eat breakfast or dessert on the bed table. Package Contain : 1 Laptop Table.","【WIDER COMPATIBILITY】This USB C Female to USB A Male adapter converter allows you to connect legacy Type-A laptops/PC,Power bank,Adapter and Charger with USB Type-C cable,USB Type-C hubs and USB Type-C peripherals. Specially compatible with iPhone 12/12 Mini/12 Pro/12 Pro Max,Samsung Galaxy Note 10/S20 Plus Ultra,Google Pixel 4/3/2 XL. ❌IMPORTANT NOTE: This product is NOT compatible with Mag-safe wireless charger due to the incompatibility of charging protocols.|【FULL FUNCTIONALITY】The USB A Male to USB C Female adapter has a multiple functions.You can easily hook up any USB-C peripherals (USB C cable, Type-C flash drive, USB-C hub) that make use of the newer USB-C connector.This USB C Female converter can be used for charging,date transfer,audio signal transmission and connecting keyboard or mouse.Additionally,it can be also used to plug into the car USB-A port.|【CHARGING AND DATA TRANSFER】This USB 2.0 adapter offers both sides date transfer speeds of up to 480Mbps between connected devices and also supports up to 2.4 Amps of power output for charging your devices,due to the built-in premium chip.Just plug into a regular USB A port,allowing you to convert to a upgraded Type C device.Truly a plug-and-play solution. ❌NOTE:NOT support video signal transmission.|【2 PACK COMPACT DESIGN】Comes with 2 packs: One for home, one for office, one for car and one carried in the bag, sticking with laptops or commonly used type C cable or others can be used as backups. Micro USB to USB C adapter is smaller than a coin, easy to carry around or toss in a bag. 15mm width allows you to plug them side by side, taking little space and working well in tight spaces.|【SAFER USING】USB C and USB A connector is made of premium aluminum alloy on the ends, designed for frequent plugging & unplugging and heat dissipation, which is safer compared to other plastic adapters. Every USB adapter has built-in 56KΩ resistor ensure safety during charging. Just plug and charge your devices with assurance.","🎁【18W Fast Charging- Always Speedy】Two ports pump out up to 18 watts of power, enabling simultaneous fast charging for two devices. 18W Type-C output port to give the latest devices a full-speed charge.|🎁【Universal Compatibility】Support all iPhone and Android Fast Charge, Quick Charge protocols like PD3.0, QC3.0, PE2.0, etc.Support all Android fast charge protocols, QC3.0, PE2.0, Dash Charge, VOOC, etc. Perfectly fits the charging needs of iPhone 13/13 Mini/13 Pro/13 Pro Max/12/11/11 Pro/11 Pro Max/XS/XR/SE/X/8 Plus, AirPods Pro, iPad series, Galaxy S21/S20 series, Note20/Note10/S10/S9, Pixel series, Nintendo Switch, and more.|🎁【PE2.0,PD 3.0 & QC 3.0】: Equipped with a 18W Power Delivery,3.0 port, and an 18W Quick Charge 3.0 port, the charger allows for charging two devices simultaneously|🎁【Safe and Reliable】This UL-certified USB C charger With the built-in intelligent chip, the wall charger matches the current as your device needs automatically, ensure safety and protection for your devices. No matter how fast it charges, you won’t have to worry about your phone heating up at all. A combination of 6 safety features that work together to provide ultimate protection for you and your devices|🎁【 Ultra-Fast Type-C Cable Included】 Oraimo 18W fast charger adapter comes with a fast charging type-c cable, It enables full speed charging and syncing to new Type-C models in the market.","👍【USB C TO USB ADAPTER】-This is a USB C FEMALE to USB MALE adapter, used to turn all you USB-A ports of laptops, chargers or other devices into a USB-C port. Gives you the ability to connect USB-C peripherals to devices with USB-A ports.|👍【HIGH-SPEED-TRANSMISSION 】 Supports Single-side USB 3.0 (USB 3.1 Gen 1) 5GB/s superspeed data transfer. Please note that this USB to USB C Adapter only supports single-sided 5Gbps high-speed transmission. The Type-C female port allows you to switch between USB 3.1 speed and USB 2.0 speed with a simple flip of the Type C plug. Now you can enjoy unparalleled transmission quality from your devices!|👍【DATA SYNC AND CHARGING】USB 3.0 (USB 3.1 Gen 1)port, up to 3A, enables up to sync and display movies or music in real time thanks to a 5Gbps transfer speed, approx 10x than USB 2.0; Also, you can edit video in camera directly via port instead of downloading files|👍【SUPERRIOR DURABILITY】Made of Premium aluminum alloy housing with specular precision process, enables plug in/out again and again. Tested and inspected meet USB Standards, fit for USB 3.0 / USB 2.0 devices, built-in 56KΩ pull-up resistor protects your devices from damage. Internal PCMA adopts EMI proof process, more stable performance.|👍【 EASY OPERATION AND PORTABILITY】-Easy to use,just PLUG and PLAY, no driver required. This USB C TO USB 3.0 adapter has the advantages of SIMPLE STRUCTURE ultra COMPACT,LIGHTWEIGHT and PORTABILITY, small enough to leave it in the USB port or anywhere in your package, take it anywhere you want!","💎[The Fastest Charge] - This iPhone USB C cable supports PD 3.0 fast charging, up to 20W with USB-C Power Delivery adapters such as 18W, 20W, 29W, 30W, 61W, or 87W. Charge your iPhone from 0% to 50% in just 25 mins, and data transfer speeds up to 480Mbps (1200 songs synced per minute)|💎[Amazing Durability] - With top-rated material and coated with premium TPE, Syncwire Apple USB C cable has exceptional durability to be bent at 90 degrees for 15000+ times and the connector is capable of holding up to 20kg of weight without falling off.|💎[Perfect Compatibility] - Syncwire Type C to lightning cable supports PD Fast Charge 3A (max) for iPhone 14, iPhone 14 Pro, iPhone 14 Pro Max, iPhone 13 mini, iPhone 13 pro max, iPhone 13, iPhone 12 Pro, iPhone 12 Pro max, iPhone 11, iPhone 11 Pro, iPhone 11 Pro Max, iPhone 8, iPhone 8 Plus, iPhone X, iPhone XS, iPhone XR, iPhone XS Max, iPad 8, iPad Pro (10.5-inch), iPad Pro (12.9-inch) 1st generation, iPad Pro (12.9-inch) 2nd generation.|Apple MFi Certified - Lightning cable ensure 100% compatibility with iPhone 14, 13, 13 Pro, 13 Pro Max, 13 Mini, 12, 12 Mini, 12 Pro, 12 Pro Max, SE 2020, iPhone 11, 11 Pro, 11 Pro Max, XR , Xs , Xs Max, X, 8, 8 plus, and iPad|20W Fast Charging Cable: USB C to lightning cable supports safe high-speed charging and fast data transfer,working better and quick charge your devices.(Note:You need to use 20W or above USB-C power adapter to achieve power delivery fast charge.)","💖 [Small Size but Powerful Effects] 2022 upgraded Pixel projector provides clear and true-to-life images that are 30% brighter than other similar projectors on the market. This tiny projector with 6.2""X4.7""X2.9"" small size and 480 grams light weight, can be easily put in your handbag for traveling, camping or other locations. Really portable projector used for family leisure.|💖 [Discover the World with Pixel!] Pixel represents a new generation of mini projectors specially designed to enrich your big screen viewing experience. This projector is built using advance construction materials which are only seen in high end projectors. Pixel is 1st mini projector to offer LTPS LCD technology which greatly enhances the image quality. LTPS display can restore complex details which are not seen on TFT or IPS display projectors.|💡 [Large Projection Size] 176 inch large projection screen brings an immersive viewing experience. It allows you to enjoy the happy home theater time with your family both indoor or outdoor. The outdoor projector provides a projection size from 35inch to 176 inch with the projection distance between 3.7ft to 23.6ft.|✔️[Multiple Devices Connection & Wide Application] Equipped with HDMI, USB, and AV interfaces, pixel projector works perfectly with smartphones, iPads, laptops, TV boxes, DVD players, PS4, USB flash disks etc. It can be applied to home theaters, video games, parties and outdoor activities. ✦✦When connect with phone, please purchase an extra HDMI adapter.|✔️[1 Year Warranty & Technical Support] We offer quick reply within 24 hours, 1-year product warranty and a lifetime after-sales service. Wzatco India professional team offers you 100% satisfaction guarantee. Just feel free to try!","📞【UTMOST CUSTOMER SUPPORT: 】24 hours WhatsApp, at ENEM, we try our best to provide great experience to you. For any reason, if you are not completely satisfied with your purchase, you may return the machine for a service or exchange within 1 year of purchase. Providing lifetime manufacturer’s support, in case of any trouble just call/WhatsApp us on +91 9958404521.|⭐【MADE IN INDIA! IMPROVED SEALING MACHINE:】ENEM sealing machine is proudly Made in India! We have used high quality transformer + High Quality Plug + heavy gauge wire so ensures good performance and optimum safety.|⭐【SUPPORT ALL HEAT SEALABLE MATERIAL BAGS: 】This is a perfect sealer to seal foil, mylar, chip, cellophane, snack, kraft, tea, polyester, P.V.A., pliofilm, tivac, saran and all other heat sealable material bags, which is ideal for household, retail, produce, grocery stores, and industrial sealing. TOP INDIAN QUALITY - so you can buy with confidence and sealing happily ever after.|⭐【ADJUSTABLE TIMER SETTING:】Adjustable heat settings for the different materials being used. For most applications, using the impulse heat sealer at heat setting of 3 is sufficient. However, different temperature settings will be more suitable for certain materials of a higher or lower melting point or thickness. The adjustable timer makes it easy to seal a variety of packaging. For example: General Plastic Bags (0-2), Aluminium Foil Bags (2-3) & Plastic Paper Bags (2-3).|⭐【AUTO – POWER OFF PROTECTION:】ENEM Plastic Packing Machine remains in standby mode when not used, thereby not utilizing power. Only when same is used for sealing, power is consumed.|⭐【UPGRADED TRANSFORMER: 】The transformer used in machine is twice bigger than any others’ substitutes which can reduce heat and work loss, make sure this table top heat impulse sealer working life is double longer than normal sealing machine. Max seal thickness:10 mils. Sealing width: 2mm.","🔥PTC CERAMIC CHIP HEATING TECHNOLOGY: The EOPORA heater is powered by PTC ceramic chip heating technology with 1 second instant heat, which can heat a room faster and quickly and efficiently heating can quickly cover your office or room in minutes.|🔥2 TEMPERATURE ADJUSTMENT MODES: High Heat (1500w) / Low Heat (1000w).The button on the back can control low temperature/off/high temperature, which is convenient to use.Our space heater features 2 different heat settings (LOW, HIGH).You can switch between different modes more flexibly according to different environments.|🔥TIP-OVER PROTECTION & OVER-HEAT PROTECTION: Room heater automatically turn off if they accidentally tip over, perfect for houses with kids and pets. When the heater overheats, the overheat protection will also automatically shut down the heater, making it safer for you to use.|🔥LOW NOISE TO USE: Room heaters have noise levels below 50 dB. Our room heater can provide warmth without interruption for the spaces you need to study, read, work and sleep.|🔥PERFECT FOR YOUR HOME OR OFFICE: The compact and portable design combined with the ergonomic built-in handle, will allow you to easily move your space heater to any room you want. Make sure your office, kitchen, bedroom, guest room, study or living room is nice and warm.|🔥1 YEAR WARRANTY: Eopora PTC Ceramic Fast Heating Room Heater has professional after -sales service and 12 -month warranty. If you have any questions or doubts, please contact us, we will solve your problems as soon as possible.","🛒【CableCreation RCA Cable】:Great for connecting portable audio devices, such as for Smartphone (iPhone), MP3 player (iPod) or tablet (iPad) to a stereo receiver, speaker or other RCA-enabled device.❗❗❗:CableCreation backed with 2 years worry-free warranty and 7*24 friendly customer service. Any further questions and suggestions, please feel free to contact us|🛒【Fantastic Sound Quality】:Oxygen Free Copper and gold plated plugs ensure optimal signal stereo audio transmission,bringing you a good feeling|🛒【Bi-directional】:This 3.5mm rca male cable works both directions,from rca out to 3.5mm in or from 3.5mm in to rca out. Please note: you cannot choose same directions for use simultaneously.It must one side in,the other side out|🛒【24K Gold Plated Connectors】:Professional quality 24k gold plated connectors which protect the cables from corrosion while ensuring a premium connection for the best possible audio transfer year after year|🛒【Compatible Device】:3.5mm MP3 to RCA Audio cable is compatible with iPhone, iPod, iPad, tablets including Google Nexus, Samsung, MP3 players, CD players, laptops, tablets and any other digital device with a 3.5mm audio jack; and home audio systems, like amplifier or receiver with RCA(RCA white/left and red/right sockets)jacks for audio inputs","🥇【Kindly NOTE before you purchase】:This is a USB-C to USB-C cable, which means it has the same USB C or Type C plug on both sides, please keep a note that this cable is not a USB-C to USB-A cable. Besides, you may need a USB C wall charger to charge your device. This product DO NOT support video output and monitor connection.|🥇【65W High Speed Charging】: Build-in updated smart chip, which makes this USB-C to USB-C PD cable strong enough to support max 3.25A current 65W power through, as well as support fast charging for more Type-C devices. You need a USB C wall charger for your device to charge and we would like you to recommend to use the original wall charger.|🥇【Compatible Devices】:This USB C to USB C cable compatible with Samsung S2

In [ ]:
data.to_csv('sample03.csv')