PANDAS

In [ ]:
!pip install pandas
!pip install numpy
import pandas as pd
import numpy as np

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [ ]:
'''A pandas series is like a column in a table. one dimwnsional array holding
any type of array'''
s1 = pd.Series([23,24,25,12,'32'])
s1

0    23
1    24
2    25
3    12
4    32
dtype: object

In [ ]:
s2 = pd.Series([23,24,25,12,'32'],index=['a','b','c','d','e'],dtype='float')
s2

a    23.0
b    24.0
c    25.0
d    12.0
e    32.0
dtype: float64

In [ ]:
#Creation of series using dictonary
s4 = pd.Series({'a':10,'b':20,'c':30})
s4

a    10
b    20
c    30
dtype: int64

DATAFRAME
A pandas data frame is a 2 dimensional data structure like a 2 dimensional array, or a table with rows and  cols

In [ ]:
d1 = pd.DataFrame([23,24,25,12,'32'])
d1

    0
0  23
1  24
2  25
3  12
4  32

In [ ]:
d2 =pd.DataFrame([[2,3,4],
                  [4,5,6],
                  [2,3,4]])
d2

   0  1  2
0  2  3  4
1  4  5  6
2  2  3  4

In [ ]:
d2 =pd.DataFrame(s2)
d2

      0
a  23.0
b  24.0
c  25.0
d  12.0
e  32.0

In [ ]:
d3 = pd.DataFrame([[2,3,4],[4,5,6],[1,2,3]],columns =['a','b','c'])
d3

   a  b  c
0  2  3  4
1  4  5  6
2  1  2  3

In [ ]:
d3 = pd.DataFrame([[2,3,4],[4,5,6],[1,2,3]],columns=['a','b','c'],index=['x','y','z'])
d3

   a  b  c
x  2  3  4
y  4  5  6
z  1  2  3

creating dataframes from list of dictionaries

In [ ]:
dic = ({'alex':1,'joe':2},{'ema':5,'dora':10,'alice':20})
pd.DataFrame(dic)

   alex  joe  ema  dora  alice
0   1.0  2.0  NaN   NaN    NaN
1   NaN  NaN  5.0  10.0   20.0

In [ ]:
d3

   a  b  c
x  2  3  4
y  4  5  6
z  1  2  3

In [ ]:
print(d3['a'])
print(d3['b'])

x    2
y    4
z    1
Name: a, dtype: int64
x    3
y    5
z    2
Name: b, dtype: int64

In [ ]:
d3['d']=d3['a']*d3['b']
d3['e']=d3['a']+d3['b']
d3

   a  b  c   d  e
x  2  3  4   6  5
y  4  5  6  20  9
z  1  2  3   2  3

In [ ]:
pop = d3.pop('b')
d3

   a  newcol2  newcol  e
x  2        2      45  5
y  4        4      60  9
z  1        1      70  3

In [ ]:
del d3['d']
d3

   a  b  e
x  2  3  5
y  4  5  9
z  1  2  3

In [ ]:
#insert
d3.insert(1,'newcol',[45,60,70])
d3

   a  newcol  b  e
x  2      45  3  5
y  4      60  5  9
z  1      70  2  3

In [ ]:
d3.insert(1,'newcol2',d3['a'])
d3

   a  newcol2  newcol  b  e
x  2        2      45  3  5
y  4        4      60  5  9
z  1        1      70  2  3

In [ ]:
#Append
d={'a':60,'newcol':70,'b':80}
df11=d2._append(d,ignore_index=True)
df11

      0     a  newcol     b
0  23.0   NaN     NaN   NaN
1  24.0   NaN     NaN   NaN
2  25.0   NaN     NaN   NaN
3  12.0   NaN     NaN   NaN
4  32.0   NaN     NaN   NaN
5   NaN  60.0    70.0  80.0

In [ ]:
import numpy as np
d4 = pd.DataFrame({'abc':np.random.randint(2,6,size=(10)),'bcd':np.random.randint(4,10,size=(10)),'cde':np.random.randint(3,10,size=(10))})
d4

   abc  bcd  cde
0    2    6    3
1    3    8    3
2    4    4    9
3    4    4    7
4    2    7    3
5    2    5    5
6    5    5    7
7    5    6    7
8    4    4    8
9    5    6    9

In [ ]:
d4.head()

   abc  bcd  cde
0    2    6    3
1    3    8    3
2    4    4    9
3    4    4    7
4    2    7    3

In [ ]:
d4.tail()

   abc  bcd  cde
5    2    5    5
6    5    5    7
7    5    6    7
8    4    4    8
9    5    6    9

In [ ]:
d4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   abc     10 non-null     int64
 1   bcd     10 non-null     int64
 2   cde     10 non-null     int64
dtypes: int64(3)
memory usage: 372.0 bytes

In [ ]:
d4.describe()

             abc        bcd        cde
count  10.000000  10.000000  10.000000
mean    3.600000   5.500000   6.100000
std     1.264911   1.354006   2.424413
min     2.000000   4.000000   3.000000
25%     2.250000   4.250000   3.500000
50%     4.000000   5.500000   7.000000
75%     4.750000   6.000000   7.750000
max     5.000000   8.000000   9.000000

In [ ]:
d4

   abc  bcd  cde
0    2    6    3
1    3    8    3
2    4    4    9
3    4    4    7
4    2    7    3
5    2    5    5
6    5    5    7
7    5    6    7
8    4    4    8
9    5    6    9

In [ ]:
print(d4.loc[3,'cde'])

7

In [ ]:
d4

   abc  bcd  cde
0    2    6    3
1    3    8    3
2    4    4    9
3    4    4    7
4    2    7    3
5    2    5    5
6    5    5    7
7    5    6    7
8    4    4    8
9    5    6    9

In [ ]:
d4.loc[4:9,['abc','cde']]

   abc  cde
4    2    3
5    2    5
6    5    7
7    5    7
8    4    8
9    5    9

In [ ]:
d4.loc[[3,4,7],['abc','cde']]

   abc  cde
3    4    7
4    2    3
7    5    7

In [ ]:
d4

   abc  bcd  cde
0    2    6    3
1    3    8    3
2    4    4    9
3    4    4    7
4    2    7    3
5    2    5    5
6    5    5    7
7    5    6    7
8    4    4    8
9    5    6    9

In [ ]:
print(d4.iloc[9,2])

9

In [ ]:
d4.iloc[2:7,[0,2]]

   abc  cde
2    4    9
3    4    7
4    2    3
5    2    5
6    5    7

In [ ]:
d4

   abc  bcd  cde
0    2    6    3
1    3    8    3
2    4    4    9
3    4    4    7
4    2    7    3
5    2    5    5
6    5    5    7
7    5    6    7
8    4    4    8
9    5    6    9

In [ ]:
d4.abc

0    2
1    3
2    4
3    4
4    2
5    2
6    5
7    5
8    4
9    5
Name: abc, dtype: int64

In [ ]:
d4.abc.values

array([2, 3, 4, 4, 2, 2, 5, 5, 4, 5])

In [ ]:
d4['sub'] = d4.abc.values - d4.cde.values - d4.bcd.values
d4

   abc  bcd  cde  sub
0    2    6    3   -7
1    3    8    3   -8
2    4    4    9   -9
3    4    4    7   -7
4    2    7    3   -8
5    2    5    5   -8
6    5    5    7   -7
7    5    6    7   -8
8    4    4    8   -8
9    5    6    9  -10

In [ ]:
a = [['Nikhil',102,15000],['Sandeep',103,20000],['Balaji',104,25000]]
dfl = pd.DataFrame(a,columns = ['name','id','salary'])
dfl

      name   id  salary
0   Nikhil  102   15000
1  Sandeep  103   20000
2   Balaji  104   25000

In [ ]:
y=dfl[dfl.salary>=20000]
print(y)
y[['id','salary']]

      name   id  salary
1  Sandeep  103   20000
2   Balaji  104   25000

    id  salary
1  103   20000
2  104   25000

In [ ]:
dfl._append({'name' : 'Karthik','id' : 105,'salary' : 30000},ignore_index=True)

      name   id  salary
0   Nikhil  102   15000
1  Sandeep  103   20000
2   Balaji  104   25000
3  Karthik  105   30000

In [ ]:
dfl = dfl._append({'name' : np.nan,'id' : 105,'salary' : 30000},ignore_index = True)
dfl

      name     id   salary
0   Nikhil  102.0  15000.0
1  Sandeep  103.0  20000.0
2   Balaji  104.0  25000.0
3      NaN  105.0  30000.0

In [ ]:
dfl.isnull()

    name     id  salary
0  False  False   False
1  False  False   False
2  False  False   False
3   True  False   False

In [ ]:
print(dfl.isnull().sum())

name      1
id        0
salary    0
dtype: int64

In [ ]:
dfl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   id      4 non-null      float64
 2   salary  4 non-null      float64
dtypes: float64(2), object(1)
memory usage: 228.0+ bytes

In [ ]:
dfl.dropna()

      name     id   salary
0   Nikhil  102.0  15000.0
1  Sandeep  103.0  20000.0
2   Balaji  104.0  25000.0

In [ ]:
dfl

      name     id   salary
0   Nikhil  102.0  15000.0
1  Sandeep  103.0  20000.0
2   Balaji  104.0  25000.0
3      NaN  105.0  30000.0

In [ ]:
dfl.fillna(value= 'abc')

      name     id   salary
0   Nikhil  102.0  15000.0
1  Sandeep  103.0  20000.0
2   Balaji  104.0  25000.0
3      abc  105.0  30000.0

In [ ]:
dfl

      name     id   salary
0   Nikhil  102.0  15000.0
1  Sandeep  103.0  20000.0
2   Balaji  104.0  25000.0
3      NaN  105.0  30000.0

In [ ]:
dfl.drop([2],axis=0,inplace=True)
dfl

      name     id   salary
0   Nikhil  102.0  15000.0
1  Sandeep  103.0  20000.0
3      NaN  105.0  30000.0

In [ ]:
import pandas as pd
df = pd.DataFrame({'Animal' : ['Falcon', 'Falcon','Parrot', 'Parrot'],'Max Speed' : [380., 370., 24., 26.],'wind Speed' : [380., 370., 24., 26.]})
df

   Animal  Max Speed  wind Speed
0  Falcon      380.0       380.0
1  Falcon      370.0       370.0
2  Parrot       24.0        24.0
3  Parrot       26.0        26.0

In [ ]:
df.groupby(['Animal']).mean()

        Max Speed  wind Speed
Animal
Falcon      375.0       375.0
Parrot       25.0        25.0

In [ ]:
df.T

                 0       1       2       3
Animal      Falcon  Falcon  Parrot  Parrot
Max Speed    380.0   370.0    24.0    26.0
wind Speed   380.0   370.0    24.0    26.0

In [ ]:
#Get Dummies
data = {'firstname': ['Arun', 'Jebu', 'Venkat', 'Rekha', 'Majid','Mohsin'],
        'lastname': ['Kumar', 'Jacob', 'Raghavan', 'Singh', 'Khan','Khan'],
        'employmenttype': ['Service', 'Business', 'Student', 'Service', 'Business','Business'],
        'country' :['India','USA','USA','Sweden','Australia','Germany']}


df = pd.DataFrame(data, columns = ['firstname','lastname','employmenttype','country'])

print(df)

  firstname  lastname employmenttype    country
0      Arun     Kumar        Service      India
1      Jebu     Jacob       Business        USA
2    Venkat  Raghavan        Student        USA
3     Rekha     Singh        Service     Sweden
4     Majid      Khan       Business  Australia
5    Mohsin      Khan       Business    Germany

In [ ]:
df1 = pd.get_dummies(df['employmenttype'], dtype=int)
df2 = pd.get_dummies(df['country'], dtype=int)
print(df1)
print(df2)

   Business  Service  Student
0         0        1        0
1         1        0        0
2         0        0        1
3         0        1        0
4         1        0        0
5         1        0        0
   Australia  Germany  India  Sweden  USA
0          0        0      1       0    0
1          0        0      0       0    1
2          0        0      0       0    1
3          0        0      0       1    0
4          1        0      0       0    0
5          0        1      0       0    0

In [ ]:
df

  firstname  lastname employmenttype    country
0      Arun     Kumar        Service      India
1      Jebu     Jacob       Business        USA
2    Venkat  Raghavan        Student        USA
3     Rekha     Singh        Service     Sweden
4     Majid      Khan       Business  Australia
5    Mohsin      Khan       Business    Germany

In [ ]:
#Concatination
import pandas as pd
india_weather = pd.DataFrame({
    "city": ["mumbai","delhi","banglore"],
    "temperature": [32,45,30],
    "humidity": [80, 60, 78]
})
india_weather

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  banglore           30        78

In [ ]:
us_weather = pd.DataFrame({
    "city": ["new york","chicago","orlando"],
    "temperature": [21,14,35],
    "humidity": [68, 65, 75]
})
us_weather

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [ ]:
df = pd.concat([india_weather, us_weather])
df

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  banglore           30        78
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [ ]:
# ignore index
df = pd.concat([india_weather, us_weather], ignore_index=True)

df

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  banglore           30        78
3  new york           21        68
4   chicago           14        65
5   orlando           35        75

In [ ]:
import pandas as pd
emp = {"Name": ["Parker", "Smith", "William", "Parker"],
"Age": [21, 32, 29, 21]}
info = pd.DataFrame(emp)
print(info)
print("--------------------")
info = info.drop_duplicates()
print(info)

      Name  Age
0   Parker   21
1    Smith   32
2  William   29
3   Parker   21
--------------------
      Name  Age
0   Parker   21
1    Smith   32
2  William   29

In [ ]:
import pandas as pd

# Create a sample DataFrame with a 'Gender' column
data = {
    'Name': ['John', 'Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Gender': ['Male', 'Female', 'Male', 'Male', 'Female', 'Female'],
    'Age': [23, 35, 45, 40, 28, 33],
    'group':["cse","ece","eee","cse","ece","ece"],
}

df1 = pd.DataFrame(data)

df1

      Name  Gender  Age group
0     John    Male   23   cse
1    Alice  Female   35   ece
2      Bob    Male   45   eee
3  Charlie    Male   40   cse
4    David  Female   28   ece
5      Eva  Female   33   ece

In [ ]:
# Convert 'Gender' column to categorical data
d = pd.Categorical(df1['group'])

# Print the categorical data
print(d)

['cse', 'ece', 'eee', 'cse', 'ece', 'ece']
Categories (3, object): ['cse', 'ece', 'eee']